-- MySQL Script generated by MySQL Workbench
-- Mon Dec 13 18:53:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`park`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`park` ;

CREATE TABLE IF NOT EXISTS `mydb`.`park` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `visitors` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `max_visitors` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`worker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`worker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`worker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `pasport_number` INT UNSIGNED NOT NULL,
  `salary` DOUBLE NOT NULL,
  `permision` INT NOT NULL,
  `park_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_worker_park_idx` (`park_id` ASC) VISIBLE,
  CONSTRAINT `fk_worker_park`
    FOREIGN KEY (`park_id`)
    REFERENCES `mydb`.`park` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attraction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`attraction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`attraction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `max_visitors` INT NOT NULL,
  `min_permision` INT NOT NULL,
  `has_option_vip` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `expiration_date` DATE NOT NULL,
  `start_date` DATE NOT NULL,
  `is_vip` TINYINT NOT NULL,
  `attraction_id` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `park_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_park1_idx` (`park_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_park1`
    FOREIGN KEY (`park_id`)
    REFERENCES `mydb`.`park` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`visitor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`visitor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `ticket_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visitor_ticket1_idx` (`ticket_id` ASC) VISIBLE,
  CONSTRAINT `fk_visitor_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `mydb`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`park_attraction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`park_attraction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`park_attraction` (
  `park_id` INT NOT NULL,
  `attraction_id` INT NOT NULL,
  INDEX `fk_park_attraction_park1_idx` (`park_id` ASC) VISIBLE,
  INDEX `fk_park_attraction_attraction1_idx` (`attraction_id` ASC) VISIBLE,
  PRIMARY KEY (`park_id`, `attraction_id`),
  CONSTRAINT `fk_park_attraction_park1`
    FOREIGN KEY (`park_id`)
    REFERENCES `mydb`.`park` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_park_attraction_attraction1`
    FOREIGN KEY (`attraction_id`)
    REFERENCES `mydb`.`attraction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paydesk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paydesk` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paydesk` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attraction_id` INT NOT NULL,
  `has_ticket` TINYINT NOT NULL,
  `park_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paydesk_park1_idx` (`park_id` ASC) VISIBLE,
  CONSTRAINT `fk_paydesk_park1`
    FOREIGN KEY (`park_id`)
    REFERENCES `mydb`.`park` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`show_entertainment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`show_entertainment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`show_entertainment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `park_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_show_park1_idx` (`park_id` ASC) VISIBLE,
  CONSTRAINT `fk_show_park1`
    FOREIGN KEY (`park_id`)
    REFERENCES `mydb`.`park` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
